# Generated by Django 3.2.3 on 2021-05-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_validenrollnos_validenrollno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validenrollno',
            options={'verbose_name': 'ValidEnrollmtNos'},
        ),
    ]
