# Generated by Django 3.2.3 on 2021-05-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_validenrollno_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validenrollno',
            options={'verbose_name': 'ValidEnrollmtNo'},
        ),
    ]
