# Generated by Django 3.2.3 on 2021-05-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_validenrollno_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='validenrollno',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
