# Generated by Django 3.2.3 on 2021-05-21 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=150)),
                ('question_body', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Bu', 'Business Law'), ('Ci', 'Civil Law'), ('Co', 'Constitutional Law'), ('Cn', 'Consumer Law'), ('Cr', 'Criminal Law'), ('Fa', 'Family Law'), ('In', 'Intellectual Property'), ('La', 'Labour'), ('Pr', 'Property Law'), ('Ta', 'Taxation')], max_length=2)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('date_asked', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_slug', models.SlugField(db_index=False, max_length=65, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_answered', models.DateTimeField(default=django.utils.timezone.now)),
                ('answer_body', models.TextField()),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('answer_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.question')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
