# Generated by Django 3.2.3 on 2021-05-25 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210521_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_slug',
        ),
    ]
