# Generated by Django 3.2.3 on 2021-06-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_question_question_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_asked']},
        ),
    ]
