# Generated by Django 3.2.3 on 2021-06-14 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_alter_question_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='downvotes',
            field=models.ManyToManyField(related_name='a_downvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvotes',
            field=models.ManyToManyField(related_name='a_upvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='question',
            name='downvotes',
        ),
        migrations.AddField(
            model_name='question',
            name='downvotes',
            field=models.ManyToManyField(related_name='q_downvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='question',
            name='upvotes',
            field=models.ManyToManyField(related_name='q_upvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
